/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package renovlunette;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application{


    public static void main(String[] args) {
        DB db = new DB();
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/menu.fxml"));
        //System.out.println(loader.load().toString());
        Scene scene = new Scene(fxmlLoader.load());
        scene.getStylesheets().add(getClass().getResource("/style.css").toExternalForm());
        primaryStage.setTitle("Renov Lunette");
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}